---
version: '3'

services:
  tinytuya2mqtt:
    image: ghcr.io/mafrosis/tinytuya2mqtt
    build:
      context: .
    volumes:
      - ./snapshot.json:/snapshot.json:ro
      - ./tinytuya2mqtt.ini:/tinytuya2mqtt.ini:ro
