---
name: gh-release
on:
  push:
    tags:
      - 'v*'

jobs:
  gh-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Wheel
        run: python -m pip wheel --no-deps --wheel-dir dist .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PAT }}
          files: |
            dist/*.whl
